CREATE TABLE message_failure_log (
  id INT NOT NULL AUTO_INCREMENT,
  uid VARCHAR(50) NOT NULL,
  msg_name VARCHAR(255) NOT NULL,
  description VARCHAR(1024) NOT NULL,
  entry_time DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE(uid)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;