CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  email_address VARCHAR(255) NOT NULL,
  password CHAR(64) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;