ALTER TABLE line_items MODIFY COLUMN primary_ad_server ENUM('OPEN_X','LIVERAIL','RED_PANDA_TIE','GENERIC_URL');
ALTER TABLE line_items MODIFY COLUMN secondary_ad_server ENUM('OPEN_X','LIVERAIL','RED_PANDA_TIE','GENERIC_URL');
ALTER TABLE line_item_ads MODIFY COLUMN primary_ad_server ENUM('OPEN_X','LIVERAIL','RED_PANDA_TIE','GENERIC_URL');
ALTER TABLE line_item_ads MODIFY COLUMN secondary_ad_server ENUM('OPEN_X','LIVERAIL','RED_PANDA_TIE','GENERIC_URL');