CREATE TABLE user_roles (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  role_name ENUM('USER','SUPER_USER','PUBLISHER_ADMIN','SITE_ADMIN','WIDGET_ADMIN','TOOLBAR_PUBLISHER'),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;