DELETE FROM user_roles WHERE role_name = 'PRODUCT_ADMIN';
DELETE FROM user_roles WHERE role_name = 'SITE_ADMIN';
ALTER TABLE user_roles CHANGE role_name role_name ENUM('USER','SUPER_USER','PUBLISHER_ADMIN','PLAYER_ADMIN','TOOLBAR_PUBLISHER','ANALYTICS', 'DEVELOPER', 'INTERNAL_USER', 'PUBLISHER_USER', 'ADVERTISING_ADMIN');
