CREATE TABLE api_keys (
  id INT NOT NULL AUTO_INCREMENT,
  widget_id INT NOT NULL,
  widget_name VARCHAR(255) NOT NULL,
  api_key VARCHAR(1024) NOT NULL,
  PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;